DROP TABLE "PUBLIC"."SUBSCRIPTION_PERIOD_HOLVI_HANDLE";
DROP TABLE "PUBLIC"."SUBSCRIPTION_PERIOD";
DROP TABLE "PUBLIC"."SERVICE";
DROP TABLE "PUBLIC"."PHONE_NUMBER";
DROP TABLE "PUBLIC"."ACCOUNT";
DROP TABLE "PUBLIC"."SECONDARY_EMAIL";
DROP TABLE "PUBLIC"."PERSON";