DROP TABLE "PUBLIC"."SUBSCRIPTION_PERIOD";
DROP TABLE "PUBLIC"."SERVICE";
DROP TABLE "PUBLIC"."PHONE_NUMBER";
DROP TABLE "PUBLIC"."ACCOUNT";
DROP TABLE "PUBLIC"."PERSON_HOLVI_HANDLE";
DROP TABLE "PUBLIC"."PERSON";