DROP TABLE "PUBLIC"."DATA_EVENT";
DROP TABLE "PUBLIC"."PERSON";
DROP TABLE "PUBLIC"."ORGANIZATION";
DROP TABLE "PUBLIC"."ACCOUNT";
DROP TABLE "PUBLIC"."MEMBERSHIP";
DROP TABLE "PUBLIC"."PHONE_NUMBER";
DROP TABLE "PUBLIC"."SERVICE";
DROP TABLE "PUBLIC"."SERVICE_SUBSCRIPTION";