#!/bin/sh

. /etc/rc.subr

name="membertrack_elock"
rcvar=membertrack_elock_enable
start_cmd="${name}_start"
stop_cmd="${name}_stop"

membertrack_elock_start()
{
    /usr/bin/start_membertrack_elock.sh \
        --device            "$membertrack_elock_device" \
        --pin               "$membertrack_elock_pin" \
        --open-time         "$membertrack_elock_open_time" \
        --close-time        "$membertrack_elock_close_time" \
        --ring-delay        "$membertrack_elock_ring_delay" \
        --whitelist-file    "$membertrack_elock_whitelist_file"
}

membertrack_elock_start()
{
    /usr/bin/stop_membertrack_elock.sh
}

load_rc_config $name
: ${membertrack_elock_enable:=no}
: ${membertrack_elock_device:=/dev/ttyUSB0}
: ${membertrack_elock_pin:=0}
: ${membertrack_elock_open_time:=6000}
: ${membertrack_elock_close_time:=3000}
: ${membertrack_elock_ring_delay:=10000}
: ${membertrack_elock_whitelist_file:=/var/lib/membertrack_elock/whitelist}

run_rc_command "$1"
